export const category = [
  {
    id: 1,
    category: "Mobile Devices",
    subCategory: ["Smartphones", "Tablets", "Smartwatches", "Fitness Trackers"],
  },
  {
    id: 2,
    category: "Mobile Accessories",
    subCategory: [
      "Phone Cases",
      "Screen Protectors",
      "Pop Sockets",
      "Stylus Pens",
      "Charging Cables",
      "Earbuds / Earphones",
      "Power Banks",
      "Wireless Chargers",
      "Car Phone Holders",
    ],
  },
  {
    id: 3,
    category: "Computing Devices",
    subCategory: ["Laptops", "Desktops", "Chromebooks", "2-in-1 Convertible"],
  },
  {
    id: 4,
    category: "Computer Accessories",
    subCategory: [
      "Keyboards (Mechanical, Wireless)",
      "Mice (Gaming, Wireless)",
      "Mouse Pads",
      "USB Hubs",
      "External Hard Drives / SSDs",
      "Flash Drives",
      "Laptop Cooling Pads",
      "Laptop Bags / Sleeves",
      "Laptop Stands",
    ],
  },
  {
    id: 5,
    category: "Audio Gadgets",
    subCategory: [
      "Bluetooth Speakers",
      "Headphones (Wired & Wireless)",
      "Soundbars",
      "Home Theater Systems",
      "Microphones",
      "Audio Interfaces",
    ],
  },
  {
    id: 6,
    category: "Camera & Video Equipment",
    subCategory: [
      "DSLRs / Mirrorless Cameras",
      "Action Cameras (GoPro)",
      "Drones",
      "Webcams",
      "Tripods / Gimbals",
      "Camera Lenses",
      "Camera Bags",
      "SD Cards / Memory Cards",
    ],
  },
  {
    id: 7,
    category: "Gaming Gadgets",
    subCategory: [
      "Gaming Consoles (PS5, Xbox Series X, Nintendo Switch)",
      "Gaming Controllers",
      "Gaming Keyboards / Mice",
      "VR Headsets",
      "Gaming Chairs",
      "Capture Cards",
      "Gaming Monitors",
    ],
  },
  {
    id: 8,
    category: "Smart Home Devices",
    subCategory: [
      "Smart Speakers (Amazon Echo, Google Nest)",
      "Smart Lights",
      "Smart Plugs",
      "Smart Thermostats",
      "Smart Locks",
      "Home Security Cameras",
      "Robot Vacuums",
    ],
  },
  {
    id: 9,
    category: "Car Tech & Accessories",
    subCategory: [
      "Dash Cams",
      "Car Chargers",
      "Bluetooth Car Kits",
      "GPS Devices",
      "Rearview Camera Systems",
    ],
  },
  {
    id: 10,
    category: "Display & Projections",
    subCategory: [
      "Monitors",
      "Projectors",
      "Monitor Mounts / Stands",
      "HDMI / Display Cables",
    ],
  },
  {
    id: 11,
    category: "Wearable Tech",
    subCategory: ["Smartwatches", "Smart Rings", "VR Headsets", "AR Glasses"],
  },
  {
    id: 12,
    category: "Travel Accessories",
    subCategory: [
      "Travel Adapters",
      "Cable Organizers",
      "Portable Wi-Fi Routers",
      "GPS Trackers",
      "E-Readers (Kindle)",
    ],
  },
];
